### ISSUE TITLE
Student names change problem

### ISSUE THREAD

**Issue by karinakozarova** [pu6ki/elsyser#4]
After changing name in settings, it is not updated everywhere.

![pic](https://user-images.githubusercontent.com/8996698/31561486-b23f9c68-b060-11e7-90c7-94eaef967e73.jpg)
![pic](https://user-images.githubusercontent.com/8996698/31561481-af51861a-b060-11e7-81ed-e74fe7cec72b.jpg)

**Comment by wencakisa** [comment]
This is not really a problem. It's happening because of the project's architecture and workflow - when you send a request to change credentials (e.g. username), the client sends a `PUT` request to the API (server) and it is updated in the profile section after the server returns a response. But it is not updated in the navigation until refresh, because it uses the currently cached username. And this is not a server problem, but a client one. But we will think of the pros and cons of updating the username in the nav until window refresh.
